removing endless loop

diff --git a/bin/tt b/bin/tt
--- a/bin/tt
+++ b/bin/tt
@@ -280,34 +280,32 @@ Darwin*)
   ;;
 Linux*)
   log "$BL Info: Running on Linux$RESET"
-  while true; do
-    hash apt && {
-      #log "${YN}Attention:${RESET} on linux uninstalling of tools is not supported!"
-      INSTALLER="apt"
-      INSTALL="sudo apt install -y"
-      UNINSTALL="sudo apt purge"
-      if has apt-rdepends; then
-        USES="apt-rdepends -r %% 2>/dev/null | grep Reverse"
-      else
-        log "${YL}Warning:$RESET cannot determine dependencies, consider installing apt-rdepends."
-        USES="echo 'no dependencies'"
-      fi
-      LIST="apt list --installed | grep -v Listing... |/usr/bin/cut -f1 -d/"
-
-    }
-    hash pacman && {
-      log "${YN}Attention:${RESET} on linux uninstalling of tools is not supported!"
-      INSTALLER="pacman"
-      INSTALL="sudo pacman -Sy"
-      USES='pacman -Qi %% | grep "Required By " | grep -v None |tr " " "\n"| wc -l'
-      LIST="pacman -Q | awk '{print \$1}'"
-    }
-    if [ -z $INSTALLER ]; then
-      err "no valid package manager found, apt and pacman are supported"
-      exit 1
+  hash apt && {
+    #log "${YN}Attention:${RESET} on linux uninstalling of tools is not supported!"
+    INSTALLER="apt"
+    INSTALL="sudo apt install -y"
+    UNINSTALL="sudo apt purge"
+    if hash apt-rdepends; then
+      USES="apt-rdepends -r %% 2>/dev/null | grep Reverse"
+    else
+      log "${YL}Warning:$RESET cannot determine dependencies, consider installing apt-rdepends."
+      USES="echo 'no dependencies'"
     fi
+    LIST="apt list --installed | grep -v Listing... |/usr/bin/cut -f1 -d/"
 
-  done
+  }
+  hash pacman && {
+    log "${YN}Attention:${RESET} on linux uninstalling of tools is not supported!"
+    INSTALLER="pacman"
+    INSTALL="sudo pacman -Sy"
+    USES='pacman -Qi %% | grep "Required By " | grep -v None |tr " " "\n"| wc -l'
+    LIST="pacman -Q | awk '{print \$1}'"
+  }
+  if [ -z $INSTALLER ]; then
+    err "no valid package manager found, apt and pacman are supported"
+    exit 1
+  fi
+
   ;;
 *)
   echo -e "$ERR Unknown Operating System:$RESET$OS_TYPE"
